/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai_tap_lon;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class n3_Frame extends javax.swing.JFrame {

    /**
     * Creates new form n3_Frame
     */
    public n3_Frame() {
        initComponents();
        cb_n3_Frame.addItem("Bạch Dương");
        cb_n3_Frame.addItem("Kim Ngưu");
        cb_n3_Frame.addItem("Song Tử");
        cb_n3_Frame.addItem("Cự Giải");
        cb_n3_Frame.addItem("Sư Tử");
        cb_n3_Frame.addItem("Xử Nữ");
        cb_n3_Frame.addItem("Thiên Bình");
        cb_n3_Frame.addItem("Bọ Cạp");
        cb_n3_Frame.addItem("Nhân Mã");
        cb_n3_Frame.addItem("Ma Kết");
        cb_n3_Frame.addItem("Bảo Bình");
        cb_n3_Frame.addItem("Song Ngư");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_n3_Frame = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        bt_n3_Frame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cb_n3_Frame.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chọn Cung Hoàng Đạo");

        bt_n3_Frame.setText("Hiển thị chi tiết");
        bt_n3_Frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_n3_FrameActionPerformed(evt);
            }
        });

        jLabel2.setMaximumSize(new java.awt.Dimension(10, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_n3_Frame)
                            .addComponent(cb_n3_Frame, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_n3_Frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_n3_Frame)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_n3_FrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_n3_FrameActionPerformed
        // TODO add your handling code here:
        setPicture setPicture = new setPicture();
        String selectedZodiac = (String) cb_n3_Frame.getSelectedItem();
        int sign = 0;
        for (int i = 0; i < cb_n3_Frame.getItemCount(); i++) {
            if (cb_n3_Frame.getItemAt(i).toString().equals(selectedZodiac)) {
                break;
            }
            sign++;
        }
        String start, end;

        if (sign == 0) {
            start = "21/3";
            end = "19/4";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\BachDuong.png", jLabel2);
        } else if (sign == 1) {
            start = "20/4";
            end = "20/5";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\KimNguu.png", jLabel2);
        } else if (sign == 2) {
            start = "21/5";
            end = "21/6";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\SongTu.png", jLabel2);

        } else if (sign == 3) {
            start = "22/6";
            end = "22/7";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\CuGiai.png", jLabel2);

        } else if (sign == 4) {
            start = "23/7";
            end = "22/8";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\SuTu.png", jLabel2);

        } else if (sign == 5) {
            start = "23/8";
            end = "22/9";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\XuNu.png", jLabel2);

        } else if (sign == 6) {
            start = "23/9";
            end = "22/10";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\ThienBinh.png", jLabel2);

        } else if (sign == 7) {
            start = "23/10";
            end = "21/11";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\BoCap.png", jLabel2);

        } else if (sign == 8) {
            start = "22/11";
            end = "21/12";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\NhanMa.png", jLabel2);

        } else if (sign == 9) {
            start = "20/1";
            end = "18/2";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\BaoBinh.png", jLabel2);
        
        } else if (sign == 10) {
            start = "22/12";
            end = "19/1";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\MaKet.png", jLabel2);
        } else {
            start = "19/2";
            end = "20/3";
            setPicture.Picture("D:\\WorkSpace\\JAVA\\Java_Practice_On_University\\src\\Bai_tap_lon\\anh\\SongNgu.png", jLabel2);
        }

        // Tính cung hoàng đạo đứng trước và cung hoàng đạo đứng sau
        String beforeZodiac = "";
        String afterZodiac = "";
        if (sign == 0) {
            beforeZodiac = "Không có";
        } else {
            beforeZodiac = cb_n3_Frame.getItemAt(sign - 1);
        }
        if (sign == 11) {
            afterZodiac = "Không có";
        } else {
            afterZodiac = cb_n3_Frame.getItemAt(sign + 1);
        }

        // In ra kết quả
        JOptionPane.showMessageDialog(this, "Ngày bắt đầu: " + start + " - Ngày kết thúc: " + end + "\nCung hoàng đạo đứng trước: " + beforeZodiac + "\nCung hoàng đạo đứng sau: " + afterZodiac);
    }//GEN-LAST:event_bt_n3_FrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n3_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n3_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n3_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n3_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n3_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_n3_Frame;
    private javax.swing.JComboBox<String> cb_n3_Frame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
